// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package me.namila.money_sync

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NativeLogPigeonPigeonUtils {

  fun createConnectionError(channelName: String): NativeLogFlutterError {
    return NativeLogFlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class NativeLogFlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()
private open class NativeLogPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class NativeLogFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by NativeLogFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeLogPigeonPigeonCodec()
    }
  }
  fun onNativeLog(priorityArg: Long, tagArg: String, messageArg: String, safeErrorCodeArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.money_sync.NativeLogFlutterApi.onNativeLog$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(priorityArg, tagArg, messageArg, safeErrorCodeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(NativeLogFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NativeLogPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
