// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package me.namila.money_sync.sms

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object SmsPermissionPigeonPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class TransportSmsPermissionStatus(val raw: Int) {
  UNAVAILABLE_IN_BUILD(0),
  NOT_REQUESTED(1),
  GRANTED(2),
  DENIED(3),
  PERMANENTLY_DENIED(4),
  REVOKED(5);

  companion object {
    fun ofRaw(raw: Int): TransportSmsPermissionStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}
private open class SmsPermissionPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TransportSmsPermissionStatus.ofRaw(it.toInt())
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TransportSmsPermissionStatus -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SmsPermissionHostApi {
  fun currentStatus(): TransportSmsPermissionStatus
  fun requestReadSms(callback: (Result<TransportSmsPermissionStatus>) -> Unit)
  fun openAppSettings()

  companion object {
    /** The codec used by SmsPermissionHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      SmsPermissionPigeonPigeonCodec()
    }
    /** Sets up an instance of `SmsPermissionHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SmsPermissionHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.money_sync.SmsPermissionHostApi.currentStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.currentStatus())
            } catch (exception: Throwable) {
              SmsPermissionPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.money_sync.SmsPermissionHostApi.requestReadSms$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestReadSms{ result: Result<TransportSmsPermissionStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SmsPermissionPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SmsPermissionPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.money_sync.SmsPermissionHostApi.openAppSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openAppSettings()
              listOf(null)
            } catch (exception: Throwable) {
              SmsPermissionPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
