// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class SmsHistoryRequest {
  SmsHistoryRequest({
    required this.fromEpochMs,
    required this.untilEpochMs,
    required this.limit,
    required this.offset,
    this.senderFilters,
  });

  int fromEpochMs;

  int untilEpochMs;

  int limit;

  int offset;

  List<String?>? senderFilters;

  List<Object?> _toList() {
    return <Object?>[fromEpochMs, untilEpochMs, limit, offset, senderFilters];
  }

  Object encode() {
    return _toList();
  }

  static SmsHistoryRequest decode(Object result) {
    result as List<Object?>;
    return SmsHistoryRequest(
      fromEpochMs: result[0]! as int,
      untilEpochMs: result[1]! as int,
      limit: result[2]! as int,
      offset: result[3]! as int,
      senderFilters: (result[4] as List<Object?>?)?.cast<String?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SmsHistoryRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fromEpochMs, other.fromEpochMs) &&
        _deepEquals(untilEpochMs, other.untilEpochMs) &&
        _deepEquals(limit, other.limit) &&
        _deepEquals(offset, other.offset) &&
        _deepEquals(senderFilters, other.senderFilters);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SmsHistoryRequest(fromEpochMs: $fromEpochMs, untilEpochMs: $untilEpochMs, limit: $limit, offset: $offset, senderFilters: $senderFilters)';
  }
}

class SmsHistoryMessage {
  SmsHistoryMessage({
    required this.providerRowId,
    required this.address,
    required this.body,
    required this.dateEpochMs,
  });

  int providerRowId;

  String address;

  String body;

  int dateEpochMs;

  List<Object?> _toList() {
    return <Object?>[providerRowId, address, body, dateEpochMs];
  }

  Object encode() {
    return _toList();
  }

  static SmsHistoryMessage decode(Object result) {
    result as List<Object?>;
    return SmsHistoryMessage(
      providerRowId: result[0]! as int,
      address: result[1]! as String,
      body: result[2]! as String,
      dateEpochMs: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SmsHistoryMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(providerRowId, other.providerRowId) &&
        _deepEquals(address, other.address) &&
        _deepEquals(body, other.body) &&
        _deepEquals(dateEpochMs, other.dateEpochMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SmsHistoryMessage(providerRowId: $providerRowId, address: $address, body: $body, dateEpochMs: $dateEpochMs)';
  }
}

class SmsHistoryPageResult {
  SmsHistoryPageResult({required this.messages, required this.hasMore});

  List<SmsHistoryMessage?> messages;

  bool hasMore;

  List<Object?> _toList() {
    return <Object?>[messages, hasMore];
  }

  Object encode() {
    return _toList();
  }

  static SmsHistoryPageResult decode(Object result) {
    result as List<Object?>;
    return SmsHistoryPageResult(
      messages: (result[0]! as List<Object?>).cast<SmsHistoryMessage?>(),
      hasMore: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SmsHistoryPageResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(messages, other.messages) &&
        _deepEquals(hasMore, other.hasMore);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SmsHistoryPageResult(messages: $messages, hasMore: $hasMore)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is SmsHistoryRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is SmsHistoryMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is SmsHistoryPageResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return SmsHistoryRequest.decode(readValue(buffer)!);
      case 130:
        return SmsHistoryMessage.decode(readValue(buffer)!);
      case 131:
        return SmsHistoryPageResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class SmsHistoryHostApi {
  /// Constructor for [SmsHistoryHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SmsHistoryHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<SmsHistoryPageResult> queryInbox(SmsHistoryRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.money_sync.SmsHistoryHostApi.queryInbox$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as SmsHistoryPageResult;
  }

  Future<int> countInbox(SmsHistoryRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.money_sync.SmsHistoryHostApi.countInbox$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<List<String?>> distinctSenders() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.money_sync.SmsHistoryHostApi.distinctSenders$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String?>();
  }
}
