name: PR Verify

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    name: Test and Analyze
    uses: ./.github/workflows/reusable-test-and-analyze.yml

  build:
    name: Build APKs
    needs: test
    uses: ./.github/workflows/reusable-build-apks.yml
    with:
      build-mode: debug
